apiVersion: v1
kind: Service
metadata:
  name: simulasitka
  labels:
    app.kubernetes.io/name: simulasitka
    app.kubernetes.io/part-of: simulasitka
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: simulasitka
    app.kubernetes.io/part-of: simulasitka
  ports:
    - name: http
      port: 80
      targetPort: 3000
