apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simulasitka
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/issue-temporary-certificate: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - secretName: simulasitka-live-tls
      hosts:
        - simulasitka.lol
        - www.simulasitka.lol
  rules:
    - host: simulasitka.lol
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: simulasitka
                port:
                  number: 80
