apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: simulasitka
resources:
  - ../../base
  - ingress.yaml
images:
  - name: registry.144.91.77.245.sslip.io/simulasitka
    newTag: ee5aff1d2d41560acd1d8bdf2ae6e32fb4f875a9
